### ISSUE TITLE
Error after install...

### ISSUE THREAD

**Issue by MrMxyzptlk** [kkew3/alfred-stackoverflow#1]
[13:01:40.168] StackExchange Search[Keyword] Processing complete
[13:01:40.171] StackExchange Search[Keyword] Passing output '' to Run Script
[13:01:40.595] ERROR: StackExchange Search[Run Script] Traceback (most recent call last):
  File "/Users/anthony/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.284B6649-341A-4E60-AEEA-FA4B01A4474C/src/so.py", line 542, in <module>
    main()
  File "/Users/anthony/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.284B6649-341A-4E60-AEEA-FA4B01A4474C/src/so.py", line 529, in main
    do_cache_sites(cd, env)
  File "/Users/anthony/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.284B6649-341A-4E60-AEEA-FA4B01A4474C/src/so.py", line 308, in do_cache_sites
    sites = request_parse_sites_api(env)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthony/Library/CloudStorage/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.284B6649-341A-4E60-AEEA-FA4B01A4474C/src/so.py", line 175, in request_parse_sites_api
    for item in resp['items']:
                ~~~~^^^^^^^^^
KeyError: 'items'
[13:01:40.596] StackExchange Search[Run Script] Processing complete
[13:01:40.604] StackExchange Search[Run Script] Passing output '' to Post Notification
[13:01:40.606] StackExchange Search[Run Script] Passing output '' to Play Sound

**Comment by kkew3** [comment]
Hi MrMxyzptlk. From the error message, I assume that the error occurred when you invoked the keyword "stack-cache-sites". I can't reproduce this issue on my mac. This is not uncommon, since the KeyError is due to unexpected response from the Internet. So to address it, 1) I restructure the project and make the installation more robust, and 2) I add more loggings, which could help locate your issue.

Currently, I suggest you:

- visit `https://api.stackexchange.com/2.2/sites?page=1&pagesize=2` and see if the browser shows up something like `{"items":[{"aliases":["https://www.stackoverflow.com","https://facebook.stackoverflow.com"],"styling":{"tag_background_color":"#E0EAF1","tag_foregroun ...` (not including the ending ellipsis). If it the response does not start with `{"items":[{`, then it's more probable that the issue origins from your network environment.
- Clone branch `issue/1` by: `git clone -b issue/1 https://github.com/kkew3/alfred-stackoverflow.git`, uninstall the problematic workflow, and reinstall the workflow in that branch according to the README in that branch. See if the issue persists.

**Comment by MrMxyzptlk** [comment]
The first bullet is correct.

I followed your 2nd bullet and now get this error when running the Alfred debugger: No module named stackexchange_search

**Comment by kkew3** [comment]
Did you configure the workflow to the right python virtualenv and do `pip install .` in that virtualenv?

**Comment by MrMxyzptlk** [comment]
Thank you.
